WIP KP-9031 Install korp auth db administration script
CSCfi/Kielipankki-korp-ansible pull request #37
Opened 2024-09-19 13:14 UTC by Traubert

2024-09-23 05:59 UTC, mmatthiesencsc requested changes
This looks great, but the user is a read-only user. It needs to be changed to korp_admin and the password is missing from our password database, too.

2024-09-23 06:26 UTC, Traubert commented
> This looks great, but the user is a read-only user. It needs to be changed to korp_admin and the password is missing from our password database, too.

Right, thanks, of course, this is fixed now (couldn't test because I didn't want to write anything!).

2024-09-30 07:24 UTC, mmatthiesencsc approved these changes
Thanks, I tested this. Works.

2024-09-30 07:24 UTC, merged

2024-09-30 07:25 UTC, aajarven commented on roles/korp-backend/tasks/main.yml
> +    state: present
Other Python requirements for the backend are installed in virtual environments ([korp_backend_venv](https://github.com/CSCfi/Kielipankki-korp-ansible/blob/main/roles/korp-backend/defaults/main.yml#L16) or (backup_venv)[https://github.com/CSCfi/Kielipankki-korp-ansible/blob/main/roles/fetch_backup/defaults/main.yml#L5]). How sure we are that installing global stuff here won't have adverse effects either now or in the future? It does make using the scripts easier though.

2024-09-30 07:31 UTC, mmatthiesencsc commented on roles/korp-backend/tasks/main.yml
> +    state: present
I think a global mysql client in this case is justified by the ease of use.

2024-09-30 07:32 UTC, Traubert commented on roles/korp-backend/tasks/main.yml
> +    state: present
It's not the only one though, see https://github.com/CSCfi/Kielipankki-korp-ansible/blob/8a8d1af3694075c9927d4f806282bb0b581ebd91/roles/create_database/tasks/main.yml#L8

What kind of adverse things are you thinking of? This is after all not a `pip` installation, but a proper system package (although from the update POV, maybe `pip` would be better - or worse, since now our pip-installed packages have not-controlled-by-us versions).

2024-09-30 07:36 UTC, Traubert commented on roles/korp-backend/tasks/main.yml
> +    state: present
It is kind of interesting that we now have two Python mysql client libraries...