Kp 8873 backup
CSCfi/Kielipankki-korp-ansible pull request #45
Opened 2024-10-11 15:30 UTC by mmatthiesencsc

Update Portal IP (high time)
Add sanat by name (since it has one)

2024-10-22 10:06 UTC, aajarven requested changes

2024-10-22 10:06 UTC, aajarven commented on roles/csc_backup/README.md
> +-- matthies 11.10.2024
If we feel like we need to explain (and I think clarification is indeed good, I often visit the wrong role), it would be better to rename the role so that there's no risk of confusion. Further, we don't usually have READMEs for roles, so we aren't likely to come looking for one even if we know that clarification is needed.

Perhaps this role could be something like `install_commvault` or, if we want to keep the role name software-agnostic, at least `install_csc_backup_tool` (though I suppose we aren't likely to switch tools often, so I would maybe go with the commvault option).

2024-10-22 10:06 UTC, aajarven commented on roles/fetch_backup/templates/get_pouta_webserver_vm_backup.j2
> +SERVER_IPS="{{ portal_server_ip }} {{ sanat_server_name }}"
Now that we don't use IP for sanat (which is smart), this is a bit weird. Maybe we could rename the variable simply to `SERVERS` and then do `for SERVER in $SERVERS` later on.

2024-11-04 15:22 UTC, mmatthiesencsc commented on roles/csc_backup/README.md
> +-- matthies 11.10.2024
I don't think we gain that much by renaming. "csc_backup" is basically short for "install_csc_backup_tool" and "install_comvault" misses the point that this role is very csc-specific., even more than fetch_backup. As to READMEs for roles. I think we should gradually add them and Github displayes them.

2024-11-04 15:30 UTC, mmatthiesencsc commented on roles/fetch_backup/templates/get_pouta_webserver_vm_backup.j2
> +SERVER_IPS="{{ portal_server_ip }} {{ sanat_server_name }}"
Yes. I opted for SERVER_LIST, since SERVERS is very close to SERVER.

2024-11-05 05:58 UTC, mmatthiesencsc commented on roles/fetch_backup/templates/get_pouta_webserver_vm_backup.j2
> +SERVER_IPS="{{ portal_server_ip }} {{ sanat_server_name }}"
And I now installed and ran the backup script manually on korp2. Works.

2024-11-05 08:24 UTC, mmatthiesencsc commented on roles/csc_backup/README.md
> +-- matthies 11.10.2024
I'll rename to install_csc_commvault

2024-11-07 09:47 UTC, mmatthiesencsc commented
@Traubert This is now also tested: ansible-playbook -vvi inventories/korp3 korp-production.yml -t install_csc_commvault_backup
The first attempt did stall, CTRL-c and rerun finished almost immediately, so could not reproduce that glitch.

2024-11-07 11:03 UTC, Traubert approved these changes
Tested to run without errors.

2024-11-07 11:04 UTC, merged