Kp 7558 korp autosync
CSCfi/Kielipankki-korp-ansible pull request #5
Opened 2023-09-26 15:03 UTC by mmatthiesencsc

This PR does several things:
- add .forward to root to forward all root mail to ling-admins
- add mail functionality to get_pouta_backups
- add auto sync script to sync korp.csc.fi with korp2

2023-09-29 14:31 UTC, aajarven requested changes
This isn't something that is strictly in the scope of this diff, but if my concerns are valid, our backup logic can sometimes try to back up wrong machines, which would be quite a major problem.

The thing is that if `SERVER_IPS` in get_pouta_backup.j2 are only updated when korp is provisioned, especially the portal IP is likely to get outdated. In the best case nobody responds from the IP and we get an error message, but if we e.g. leave the old production server hanging around after portal update, the worst case scenario is that we "successfully" back that up for months on end while capturing none of the changes done in the actual production server.

I guess these would need to be updated as a part of the provisioning of the backed-up services.

2023-10-02 07:34 UTC, mmatthiesencsc commented
Yes, my bad, conflicts fixed.

2023-10-02 14:04 UTC, aajarven commented on roles/fetch_backup/templates/get_pouta_backup.j2
> +   mail_log "No logfile!"
Getting an email with this as the only error description might be somewhat confusing for someone who is not already familiar with the backup system (likely to happen e.g. during summer holidays). In the worst case this results in no action being taken despite the backups not being up to date. Maybe we could add a message body that fleshes the problem out a bit: that we expect to produce an empty log file on successful backup fetching run, and we didn't, so the data has likely not been backed up successfully.

2023-10-04 05:49 UTC, mmatthiesencsc commented on roles/fetch_backup/templates/get_pouta_backup.j2
> +   mail_log "No logfile!"
I was actually also thinking that no body was a bit of a waste, but I did not really come up with good content. Thanks, fixed.

2023-10-04 14:18 UTC, aajarven commented on roles/fetch_backup/templates/get_pouta_webserver_vm_backup.j2
> +# backs up lamp/tomcat servers, (e.g. portal, metashare, webanno, specified by $SERVER_IPS) using $BACKUP_GLOB to $LOCAL_BACKUP_DIR
The first comment line no longer matches the file name (though I don't know if repeating it adds value anyway, so might be better to just remove instead of updating?).

Further, why we mention LAMP or tomcat here (or in other comments) at all? To me this scripts looks totally content-agnostic: as long as we have access and the server has a file that matches the glob, this could as well be backing up comic_collection_backup.tar.gz from mustavaris.whatever.csc.fi

2023-10-04 14:36 UTC, mmatthiesencsc commented on roles/fetch_backup/templates/get_pouta_webserver_vm_backup.j2
> +# backs up lamp/tomcat servers, (e.g. portal, metashare, webanno, specified by $SERVER_IPS) using $BACKUP_GLOB to $LOCAL_BACKUP_DIR
I indeed missed the filename, removed it.
While you are technically right about the script being agnostic, I think a bit of context cannot hurt.

2023-10-05 08:46 UTC, aajarven approved these changes

2023-10-05 11:45 UTC, mmatthiesencsc commented
I renamed and refactored the "get_pouta_backup", added context for the missing log error. "LAMP" is strictly not 100% correct

2023-10-06 06:55 UTC, merged